# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      - image: mongo: 4.0.0
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/reviews

    steps:
      - checkout

      - run: 
        name: update-npm
        command: 'sudo npm install -g npm@6'

      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "package.json" }}

      - run:
        name: install-npm-wee
        command: npm install

      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
        name: test
        command: npm test

       - run:
        name: code-coverage
        command: './node_modules/.bin/nyc report --reporter=text-lcov'

      - store_artifacts:
          path: test-results.xml
          prefix: tests

      - store_artifacts:
          path: coverage
          prefix: coverage

      - store_test_results:
          path: test-results.xml

