version: '3'

services:
  survey:
    build: .
    depends_on:
      - "database"
    ports: 
      - "3003:3003"

  database:
    image: mongo:latest
    ports:
      - "27017:27017"

  # mongo-seed:
  #   build: seed/database-population.js
  #   links:
  #     - mongodb
