version: '3'

services:
  server:
    image: davidpc/reviews_survey
    depends_on:
      - "database"
    ports: 
      - "3003:3003"

  database:
    image: mongo:latest
    ports:
      - "27017:27017"

  # mongo-seed:
  #   build: seed/database-population.js
  #   links:
  #     - mongodb
